aws:
  s3:
    mock: false

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-izp2xgfyxw-stack-awsebrdsdatabase-urtwcqffty34.cph7lrr0ak8g.us-east-1.rds.amazonaws.com:5432/member
    username: ninjacyborg
    password: password