name: CI - Build Backend

on:
  pull_request:
    branches:
      - main
    # path of current folder
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15.3
        # Provide the password for postgres
        # db in elastic beanstalk
        env:
          POSTGRES_USER: ninjacyborg
          POSTGRES_PASSWORD: password
          POSTGRES_DB: member
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit & Integration Tests with Maven
        run: mvn -ntp -B verify